version: '3.8'

services:
    drugs-db:
        build: 
            context: ./DrugsDB
            dockerfile: Dockerfile
        container_name: drugs-db
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
            MSSQL_SA_PASSWORD: "PastaGongDuck38*"
        ports: 
            - "1433:1433"
            - "1400:1433"
        volumes:
        - db_data:/var/opt/mssql
        restart: always  # Automatically restart on failure
        networks:
        - Drugs-network 

    api-service:
        build:
            context: ./ICE4
            dockerfile: Dockerfile 
        container_name: api-service
        environment:
            SQL_CONNECTION_STRING: "Server=drugs-db,1433;Database=Drugs;User Id=sa;Password=PastaGongDuck38*;Encrypt=False;MultipleActiveResultSets=True;"
            ASPNETCORE_ENVIRONMENT: "Development"
        ports:
        - "5000:8080"
        depends_on:
            drugs-db:
                condition: service_healthy
        networks:
        - Drugs-network        
 
networks:
    Drugs-network:
        driver: bridge

volumes:
    db_data: