USE master;
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'Drugs2')
BEGIN
    CREATE DATABASE Drugs2;
END
GO


Use Drugs2;
GO

Create table Product(
    id INT PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(50) NOT NULL,
    Category VARCHAR(50) NOT NULL,
    Price float NOT NULL
);

GO

INSERT INTO Product (Name, Category, Price)
VALUES
    ('A2', 'Narcotics', 60.75),
    ('acetylfentanyl', 'Narcotics', 120.00),
    ('Acid', 'Hallucinogens', 15.25),
    ('Aerosols', 'Narcotics', 8.90),
    ('Agaric', 'Hallucinogens', 20.00),
    ('Alcohol', 'Narcotics', 12.50),
    ('Alpha-Methyltryptamine', 'Hallucinogens', 35.80),
    ('Alprazolam', 'Prescriptions', 5.75),
    ('Amani', 'Hallucinogens', 22.30),
    ('Amphetamine', 'Narcotics', 25.00),
    ('Amphetamine Sulphate', 'Narcotics', 27.50),
    ('Amsterdam Gold', 'Narcotics', 18.90),
    ('AMT', 'Hallucinogens', 33.20),
    ('Amt freebase', 'Hallucinogens', 32.10),
    ('Amyl nitrate', 'Narcotics', 10.25),
    ('Amyls', 'Narcotics', 9.80),
    ('Anabolic steroids', 'Prescriptions', 55.60),
    ('Angel dust', 'Hallucinogens', 40.00),
    ('Annihilation', 'Narcotics', 19.95),
    ('Ayahuasca', 'Hallucinogens', 50.00),
    ('Baccy', 'Narcotics', 7.50),
    ('Balloons', 'Narcotics', 6.25),
    ('Banshee dust', 'Prescriptions', 15.00),
    ('Bars', 'Prescriptions', 4.90),
    ('Base', 'Narcotics', 26.75),
    ('Bath Salts', 'Narcotics', 30.00),
    ('Benzo Fury', 'Narcotics', 28.50),
    ('Benzodiazepines', 'Prescriptions', 6.00),
    ('Benzofuran compounds', 'Narcotics', 29.25),
    ('Benzos', 'Prescriptions', 5.50),
    ('Benzylpiperazine', 'Narcotics', 22.80),
    ('Bevvy', 'Narcotics', 11.90),
    ('Bhang', 'Narcotics', 14.50),
    ('Billy', 'Narcotics', 24.75),
    ('Black Mamba', 'Narcotics', 17.00),
    ('Blast', 'Narcotics', 23.25),
    ('Blotter', 'Hallucinogens', 16.50),
    ('Blow', 'Narcotics', 80.00),
    ('Blue Cheese', 'Narcotics', 18.25),
    ('Blues', 'Prescriptions', 5.25),
    ('Bolts Extra Strength', 'Narcotics', 21.90),
    ('Bom-25', 'Hallucinogens', 45.00),
    ('Bombay Blue Extreme', 'Narcotics', 19.50),
    ('Bonsai', 'Prescriptions', 7.80),
    ('Bonsai supersleep', 'Prescriptions', 8.00),
    ('Bounce', 'Narcotics', 32.50),
    ('Brown', 'Narcotics', 90.00),
    ('Bubble', 'Narcotics', 31.75),
    ('Bud', 'Narcotics', 15.00),
    ('Burst', 'Prescriptions', 14.25),
    ('Butane', 'Narcotics', 9.00),
    ('Butylone', 'Narcotics', 27.00),
    ('BZP', 'Narcotics', 20.50),
    ('Cannabis', 'Narcotics', 12.00),
    ('carfentanyl', 'Narcotics', 130.00),
    ('Cathinones', 'Narcotics', 28.00),
    ('Chang', 'Narcotics', 82.50),
    ('Charge', 'Narcotics', 33.00),
    ('Chargers', 'Narcotics', 6.50),
    ('Charlie', 'Narcotics', 87.00),
    ('Chat', 'Narcotics', 10.00),
    ('Chicken Fever', 'Narcotics', 40.00),
    ('Chicken Yellow', 'Narcotics', 41.00),
    ('Ching', 'Narcotics', 88.00),
    ('Chroming', 'Narcotics', 8.75),
    ('Ciggies', 'Narcotics', 7.00),
    ('Clockwork Orange', 'Narcotics', 16.80),
    ('Co-codamol', 'Prescriptions', 4.50),
    ('Cocaine', 'Narcotics', 90.00),
    ('Codeine', 'Prescriptions', 5.00),
    ('Codis500', 'Prescriptions', 4.75),
    ('Coke', 'Narcotics', 89.50),
    ('Cosmic Kelly', 'Narcotics', 24.00),
    ('Cough Syrup', 'Prescriptions', 4.25),
    ('Crack', 'Narcotics', 95.00),
    ('Crank', 'Narcotics', 65.00),
    ('Crystal', 'Narcotics', 70.00),
    ('Crystal Meth', 'Narcotics', 75.00),
    ('D2Pm', 'Narcotics', 38.00),
    ('Depas', 'Prescriptions', 6.50),
    ('Desoxypipradrol', 'Narcotics', 39.00),
    ('Dezolam', 'Prescriptions', 6.75),
    ('Diamorphine', 'Prescriptions', 10.00),
    ('Diazepam', 'Prescriptions', 5.80),
    ('Dimethocaine', 'Narcotics', 35.50),
    ('Dimethyltryptamine', 'Hallucinogens', 48.00),
    ('Dimitri', 'Hallucinogens', 47.50),
    ('Dizzle', 'Narcotics', 72.00),
    ('DMT', 'Hallucinogens', 49.00),
    ('Dope', 'Narcotics', 13.50),
    ('Dots', 'Hallucinogens', 17.00),
    ('Double Stacked', 'Narcotics', 42.00),
    ('Downers', 'Prescriptions', 5.90),
    ('Dr Death', 'Narcotics', 43.00),
    ('Draw', 'Narcotics', 14.00),
    ('Drone', 'Narcotics', 34.00),
    ('Drop', 'Hallucinogens', 15.75),
    ('Dusting', 'Narcotics', 9.25),
    ('e-cigarettes', 'Narcotics', 20.00),
    ('e-cigs', 'Narcotics', 19.50),
    ('e-hookah', 'Narcotics', 22.00),
    ('e-liquids', 'Narcotics', 15.75),
    ('Eclipse', 'Hallucinogens', 25.00),
    ('Ecsess', 'Narcotics', 18.50),
    ('Ecstasy', 'Narcotics', 70.00),
    ('Energy-1', 'Narcotics', 36.00),
    ('Energy1', 'Narcotics', 35.75),
    ('Eric 3', 'Narcotics', 31.00),
    ('Esp', 'Narcotics', 23.50),
    ('Ethylphenidate', 'Prescriptions', 16.00),
    ('Eticalm', 'Prescriptions', 6.25),
    ('Etilaam', 'Prescriptions', 6.30),
    ('Etisedan', 'Prescriptions', 6.40),
    ('Etizola', 'Prescriptions', 6.60),
    ('Etizolam', 'Prescriptions', 6.80),
    ('Euphoria', 'Narcotics', 24.50),
    ('Evoke', 'Prescriptions', 14.50),
    ('Exodus', 'Narcotics', 25.25),
    ('Exodus Damnation', 'Narcotics', 19.75),
    ('Fake cocaine', 'Prescriptions', 13.00),
    ('Fast Lane', 'Narcotics', 26.00),
    ('Fenazepam', 'Prescriptions', 7.50),
    ('Fentanyl', 'Narcotics', 110.00),
    ('fentanyls', 'Narcotics', 115.00),
    ('Flake', 'Narcotics', 91.00),
    ('Freebase', 'Narcotics', 92.00),
    ('Frenzy', 'Narcotics', 27.25),
    ('Gabapentin', 'Prescriptions', 8.50),
    ('Ganja', 'Narcotics', 13.75),
    ('Gas', 'Narcotics', 8.50),
    ('Gases', 'Narcotics', 8.25),
    ('Gbh', 'Narcotics', 30.50),
    ('Gbl', 'Narcotics', 31.00),
    ('Gear', 'Narcotics', 93.00),
    ('Geebs', 'Narcotics', 29.50),
    ('GHB & GBL', 'Narcotics', 32.00),
    ('Glass', 'Narcotics', 76.00),
    ('Glue sniffing', 'Narcotics', 9.50),
    ('Glues', 'Narcotics', 9.75),
    ('Glues, gases and aerosols', 'Narcotics', 10.00),
    ('Gogaine', 'Prescriptions', 14.75),
    ('Grass', 'Narcotics', 14.25),
    ('Happy Pills', 'Narcotics', 22.50),
    ('Hash', 'Narcotics', 15.25),
    ('Hashish', 'Narcotics', 15.50),
    ('Herb', 'Narcotics', 14.75),
    ('Heroin', 'Narcotics', 95.00),
    ('Hippie Crack', 'Narcotics', 6.75),
    ('Hog', 'Hallucinogens', 41.00),
    ('Holy sage', 'Hallucinogens', 26.00),
    ('Hookah', 'Narcotics', 21.00),
    ('Horse', 'Narcotics', 96.00),
    ('Hubble bubble', 'Narcotics', 20.50),
    ('Huffing', 'Narcotics', 9.25),
    ('Ice', 'Narcotics', 77.00),
    ('Indopan', 'Hallucinogens', 36.00),
    ('Inhalants', 'Narcotics', 8.00),
    ('Inxity', 'Prescriptions', 6.90),
    ('Ivory wave', 'Narcotics', 37.00),
    ('Juice', 'Prescriptions', 52.00),
    ('K2', 'Narcotics', 17.50),
    ('Ket', 'Narcotics', 46.00),
    ('Ketamine', 'Narcotics', 47.00),
    ('Khat', 'Narcotics', 11.00),
    ('Killer', 'Narcotics', 44.00),
    ('Laughing Gas', 'Narcotics', 7.00),
    ('Legal E', 'Narcotics', 23.75),
    ('Legal X', 'Narcotics', 24.25),
    ('Liberties', 'Hallucinogens', 21.00),
    ('Liberty Caps', 'Hallucinogens', 22.00),
    ('Linctus', 'Prescriptions', 9.00),
    ('Liquid Acid', 'Hallucinogens', 16.75),
    ('Liquid Ecstasy', 'Narcotics', 33.50),
    ('Liquid Gold', 'Narcotics', 10.50),
    ('LSD', 'Hallucinogens', 18.00),
    ('Lucy', 'Hallucinogens', 17.50),
    ('Lyrica', 'Prescriptions', 8.75),
    ('M-CAT', 'Narcotics', 34.50),
    ('M-Smack', 'Narcotics', 35.00),
    ('M1', 'Narcotics', 28.50),
    ('Magic Crystals', 'Narcotics', 29.00),
    ('Magic mushrooms', 'Hallucinogens', 23.00),
    ('Magics', 'Hallucinogens', 23.50),
    ('Mandy', 'Narcotics', 71.00),
    ('Marijuana', 'Narcotics', 13.25),
    ('Mary Joy', 'Narcotics', 18.00),
    ('MC', 'Narcotics', 36.00),
    ('MD', 'Narcotics', 69.00),
    ('Mdat', 'Narcotics', 32.50),
    ('MDMA', 'Narcotics', 73.00),
    ('Mdpv', 'Narcotics', 30.00),
    ('Melanotan', 'Prescriptions', 53.00),
    ('Meow Meow', 'Narcotics', 37.00),
    ('Meph', 'Narcotics', 38.00),
    ('Mephedrone', 'Narcotics', 39.00),
    ('Mescaline', 'Hallucinogens', 55.00),
    ('Meth', 'Narcotics', 78.00),
    ('methadone', 'Prescriptions', 9.50),
    ('Methadone', 'Prescriptions', 9.75),
    ('Methamphetamine', 'Narcotics', 80.00),
    ('Methoxetamine (MXE)', 'Narcotics', 48.00),
    ('Methylnaphthidate', 'Prescriptions', 15.50),
    ('Methylone', 'Narcotics', 31.00),
    ('Methylphenidate', 'Prescriptions', 16.50),
    ('Mexican magic mint', 'Hallucinogens', 27.00),
    ('Mexxy', 'Narcotics', 49.00),
    ('Mexy', 'Narcotics', 50.00),
    ('Micro Dot', 'Hallucinogens', 18.50),
    ('Miow', 'Narcotics', 40.00),
    ('Mitsubishi Turbo', 'Narcotics', 45.00),
    ('Mixture', 'Prescriptions', 9.25),
    ('Mket', 'Narcotics', 51.00),
    ('Molly', 'Narcotics', 74.00),
    ('Monkey Dust', 'Narcotics', 29.50),
    ('Morphine', 'Prescriptions', 10.50),
    ('Moxy', 'Narcotics', 52.00),
    ('Mozun', 'Prescriptions', 7.00),
    ('Mushies', 'Hallucinogens', 24.00),
    ('Mxe', 'Narcotics', 53.00),
    ('N-bomb', 'Hallucinogens', 46.00),
    ('Naphyrone', 'Narcotics', 37.50),
    ('Nemesis', 'Narcotics', 25.75),
    ('Neurontin', 'Prescriptions', 8.25),
    ('Nexus', 'Hallucinogens', 60.00),
    ('Nic', 'Narcotics', 5.00),
    ('nitazenes', 'Narcotics', 125.00),
    ('Nitrous oxide', 'Narcotics', 7.50),
    ('Nootropics', 'Prescriptions', 45.00),
    ('Nopaine', 'Prescriptions', 15.75),
    ('Nos', 'Narcotics', 7.25),
    ('Noz', 'Narcotics', 7.75),
    ('Nps', 'Narcotics', 34.00),
    ('Nrg-1', 'Narcotics', 38.00),
    ('Nrg1', 'Narcotics', 37.75),
    ('Nurofen Plus/Max', 'Prescriptions', 4.80),
    ('Opiate/Opioid painkillers', 'Prescriptions', 11.00),
    ('Oxycodone', 'Prescriptions', 12.00),
    ('oxycodone', 'Prescriptions', 12.50),
    ('Party Pills', 'Narcotics', 26.50),
    ('Pasaden', 'Prescriptions', 7.10),
    ('Paste', 'Narcotics', 28.00),
    ('PCP', 'Hallucinogens', 42.00),
    ('Peace pills', 'Hallucinogens', 43.00),
    ('Pebbles', 'Narcotics', 89.00),
    ('Pep', 'Narcotics', 27.50),
    ('Pep Love', 'Narcotics', 28.25),
    ('Pep Stoned', 'Narcotics', 28.75),
    ('Pep Twisted', 'Narcotics', 29.25),
    ('Percy', 'Narcotics', 90.50),
    ('Petrol', 'Narcotics', 10.75),
    ('Peyote', 'Hallucinogens', 56.00),
    ('PeyoteButtons', 'Hallucinogens', 57.00),
    ('Phenazepam', 'Prescriptions', 7.75),
    ('Phencyclidine', 'Hallucinogens', 44.00),
    ('Physeptone', 'Prescriptions', 9.80),
    ('Pills', 'Narcotics', 75.00),
    ('Pink Ecstasy', 'Narcotics', 46.00),
    ('Pink Mcdonalds', 'Narcotics', 47.00),
    ('Piperazines', 'Narcotics', 30.00),
    ('PlantFood', 'Narcotics', 35.00),
    ('PMA', 'Narcotics', 48.00),
    ('Pmma', 'Narcotics', 49.00),
    ('Pollen', 'Narcotics', 15.75),
    ('Poppers', 'Narcotics', 11.00),
    ('Posh', 'Prescriptions', 16.25),
    ('Pot', 'Narcotics', 14.50),
    ('Pregabalin', 'Prescriptions', 9.00),
    ('Propylphenidate', 'Prescriptions', 17.00),
    ('Puff', 'Narcotics', 15.00),
    ('puff bars', 'Narcotics', 18.00),
    ('Purple wave', 'Narcotics', 39.00),
    ('Pyrovalerone', 'Narcotics', 32.00),
    ('Qaadka', 'Narcotics', 11.25),
    ('Qat', 'Narcotics', 11.50),
    ('Quat', 'Narcotics', 11.75),
    ('Rapture', 'Narcotics', 29.50),
    ('Rave', 'Narcotics', 38.50),
    ('Red Mitsubishi', 'Narcotics', 50.00),
    ('Resin', 'Narcotics', 16.00),
    ('Rhino ket', 'Narcotics', 54.00),
    ('Ritalin', 'Prescriptions', 17.50),
    ('Rocks', 'Narcotics', 91.50),
    ('Roflcoptr', 'Narcotics', 55.00),
    ('Rogan', 'Hallucinogens', 48.50),
    ('Rohypnol', 'Prescriptions', 6.00),
    ('Roids', 'Prescriptions', 54.00),
    ('Roll-ups', 'Narcotics', 7.50),
    ('Rollies', 'Narcotics', 7.75),
    ('Roofies', 'Prescriptions', 6.25),
    ('Salvia', 'Hallucinogens', 28.00),
    ('Sensi', 'Narcotics', 16.25),
    ('Seventh-Heaven', 'Hallucinogens', 62.00),
    ('Shisha', 'Narcotics', 21.50),
    ('Shrooms', 'Hallucinogens', 26.00),
    ('Sildenafil', 'Prescriptions', 40.00),
    ('Silver Bullet', 'Narcotics', 30.50),
    ('Sinsemilla', 'Narcotics', 16.50),
    ('Skag', 'Narcotics', 97.00),
    ('Skunk', 'Narcotics', 17.00),
    ('Smack', 'Narcotics', 98.00),
    ('Smart drugs', 'Prescriptions', 42.00),
    ('SmileyPaper', 'Hallucinogens', 47.00),
    ('Smileys', 'Narcotics', 31.00),
    ('Smokes', 'Narcotics', 8.00),
    ('Sniff', 'Narcotics', 92.00),
    ('Snow', 'Narcotics', 93.00),
    ('Solvents', 'Narcotics', 10.25),
    ('Special K', 'Narcotics', 56.00),
    ('Speed', 'Narcotics', 29.00),
    ('Spice', 'Narcotics', 19.00),
    ('Stones', 'Narcotics', 94.00),
    ('Sulph', 'Narcotics', 29.50),
    ('Super K', 'Narcotics', 57.00),
    ('Sylazepam', 'Prescriptions', 7.25),
    ('Synthetic cannabinoids', 'Narcotics', 20.00),
    ('Synthetic opioids', 'Narcotics', 135.00),
    ('Syrup', 'Prescriptions', 5.50),
    ('T-7', 'Hallucinogens', 63.00),
    ('Tab', 'Hallucinogens', 19.00),
    ('Tai High Hawaiian Haze', 'Narcotics', 20.50),
    ('Temazepam', 'Prescriptions', 6.50),
    ('The businessman’s trip', 'Hallucinogens', 49.00),
    ('The Good Stuff', 'Narcotics', 31.50),
    ('Tina And Christine', 'Narcotics', 81.00),
    ('TNT', 'Narcotics', 11.25),
    ('Toot', 'Narcotics', 95.00),
    ('Tooting', 'Narcotics', 10.50),
    ('Tramadol', 'Prescriptions', 13.00),
    ('tramadol', 'Prescriptions', 13.25),
    ('Tramal', 'Prescriptions', 13.50),
    ('Tripper', 'Hallucinogens', 19.50),
    ('Trips', 'Hallucinogens', 20.00),
    ('Tripstacy', 'Hallucinogens', 64.00),
    ('Ultram', 'Prescriptions', 13.75),
    ('Valium', 'Prescriptions', 6.75),
    ('Vallies', 'Prescriptions', 6.80),
    ('VanillaSky', 'Narcotics', 40.00),
    ('Viagra', 'Prescriptions', 41.00),
    ('Vitamin K', 'Narcotics', 58.00),
    ('Volatile substances', 'Narcotics', 11.50),
    ('Wash', 'Narcotics', 96.00),
    ('Weed', 'Narcotics', 17.50),
    ('Whippits', 'Narcotics', 8.00),
    ('White', 'Narcotics', 97.00),
    ('White Magic', 'Narcotics', 41.00),
    ('WhitePearl', 'Narcotics', 32.00),
    ('Whizz', 'Narcotics', 30.00),
    ('Window', 'Hallucinogens', 20.50),
    ('Xanax', 'Prescriptions', 7.00),
    ('Xans', 'Prescriptions', 7.10),
    ('Xtc', 'Narcotics', 76.00),
    ('Yaba', 'Narcotics', 82.00),
    ('Zoly', 'Prescriptions', 7.20);
    
    GO